apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: h2nosq234-python 
  janus-idp.io/tekton: h2nosq234-python
  backstage.io/kubernetes-id: h2nosq234-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: h2nosq234-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  